### PR TITLE
Uses preferredMaxLayoutWidth to calculate height. Adds example for dynamic height in table view

### PR DESCRIPTION
**Pull request by derpoliuk**
I struggled to get right height for the cells at the screen when view is loaded. All other cells are working perfectly.

I fixed it using preferredMaxLayoutWidth internally to calculate height and setting this property from view controller.

I added example for dynamic height in table view.

### CODE REVIEW

**Comment by bevbomb** [comment]
I had the same issue! Also I found that truncating doesn't seem to work, instead the text is layed out in full and got cut off weird

**Comment by SebastienThiebaud** [comment]
Poke @humblehacker. Does that sound ok to you?

**Comment by humblehacker** [comment]
This will work, but at the expense of requiring that your view controller be aware of the internal layout of the table view cells.

Take a look at this and see if it works for you: https://github.com/derpoliuk/STTweetLabel/compare/master...humblehacker:master

**Comment by derpoliuk** [comment]
@humblehacker it works for me. 

But from my perspective it is less harmful if view controller will know about internal layout vs reloading table view on `viewDidAppear` - this is not the best UX.

**Comment by derpoliuk** [comment]
@humblehacker it works for me. 

But from my perspective it is less harmful if view controller will know about internal layout vs reloading table view on `viewDidAppear` - this is not the best UX.

**Pull request closed without merging**
